services:
  # Backend API service
  - type: web
    name: splinter-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install:all && npm run build:backend
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RIOT_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "24h"
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false

  # Frontend static site  
  - type: web
    name: splinter-frontend
    env: static
    plan: free
    buildCommand: npm run install:all && npm run build:frontend
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: splinter-api
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html